# Generated by Django 2.2.6 on 2019-10-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    def create_currencies(apps, schema_editor):
        CurrencyRate = apps.get_model('exchange', 'CurrencyRate')

        CurrencyRate.objects.create(name='Czech koruna', abbreviation='CZK')
        CurrencyRate.objects.create(name='Czech koruna', abbreviation='PLN')
        CurrencyRate.objects.create(name='Euro', abbreviation='EUR')
        CurrencyRate.objects.create(name='US dollar', abbreviation='USD')

    operations = [
        migrations.RunPython(create_currencies)
    ]
